chapters: 
  - name: "Salah (Prayers)"
    link: /salah/
  - name: "Hajj (Pilgrimage) and 'Umrah (Lesser pilgrimage)"
    link: /hajj-umrah/
  - name: "Zakah (Obligatory charity) and Sadaqah (Voluntary charity)"
    link: /zakah/
  - name: "Shawm (Fasting)"
    link: /shawm/
  - name: "Taharah (Purification)"
    link: /taharah/
  - name: "Jihad"
    link: /jihad/
  - name: "Sirah (The Prophet's biography)"
    link: /sirah/
  - name: "Tafsir (Exegesis)"
    link: /tafsir/
  - name: "Al-Nikah (Marriage)"
    link: /nikah/
  - name: "Al-Talaq (Divorce)"
    link: /talaq/
  - name: "Funerals"
    link: /funerals/
  - name: "Kafarah (Expiation)"
    link: /kafarah/
  - name: "Oaths"
    link: /oaths/
  - name: "Miscellaneous"
    link: /misc/
  - name: "Women"
    link: /women/
  - name: "Sects and Groups"
    link: /sects/
  - name: "Zina (Adultery)"
    link: /zina/
  - name: "Madhabs (Schools of jurisprudence)"
    link: /madhabs
  - name: "Tawassul"
    link: /tawassul/
  - name: "Homosexuals and lesbianism"
    link: /homosexuals/
  - name: "Waqf (Endowment)"
    link: /waqf/
  - name: "Al-Buyu' (Sales), Transactions, Riba (Usury/Interest), Loan"
    link: /al-buyu/
  - name: Non-Muslim
    link: /sects/non-muslim/
  - name: "Al-Wala' Wal-Bara' (Loyalty and dissassiation for Allah's sake)"
    link: /aqidah/walabara/
  - name: "Family and relatives"
    link: /relatives/
  - name: "Mawlids (Celebrations)"
    link: /mawlids/
  - name: "Luqatah (A lost item found by someone else)"
    link: /luqatah/
  - name: "The Laqit (Foundling)"
    link: /foundling/
  - name: Insurance
    link: /insurance/
  - name: Inheritance
    link: /inheritance/
  - name: Treatments and Medicines
    link: /treatments/
  - name: Fitnahs
    link: /fitnahs/
  - name: Signs of the Hour
    link: /doomsday/
  - name: "Rulership, Kingship"
    link: /rulership/
  - name: "Ahl Al-Fatrah"
    link: /ahl-fatrah/
  - name: "Knowledge"
    link: /jihad/knowledge/
  - name: "Hijrah"
    link: /jihad/hijrah/
    
pagination:
  next: Next
  prev: Prev

page: 
  no-fatwas: "There are no fatwas for this topic."
  chairman: Chairman
  deputy_chairman: Deputy Chairman
  members: Members
  404: "Page not found. The page you are looking for is either under construction or is temporarily not available."

post: 
  readmore: Read more
  source: Source
  muftis: Muftis
  published: Published on
  share: Share on
  dua: May Allah guide us and all Muslims to useful knowledge and good deeds, grant us the ability to understand and follow the path of the master of the messengers, his Sahabah, and their followers in righteousness! May Allah protect us and all Muslims from the delusive trials, the insinuations of Satan, and from committing Bid'ah (innovations in Religion)! He is the One Who is capable to do so. May peace and blessings be upon our Prophet Muhammad, his family, and his Companions!.

sidebar_menu:
  - name: Home
    link: /
    active: home
  - name: Muqolat
    link: /muqolat/
    active: muqolat
  - name: Fatwas
    link: /fatwas/
    active: fatwas
  - name: Browse
    link: /topic
    active: topic
  - name: Audios
    link: /audios/
    active: downloads
  - name: Wahhabiyah
    link: /wahhabism/
    active: wahhabiyah
  - name: Refutals
    link: /refutations/
    active: refutations
    
social: 
  fb: Facebook
  gplus: Google plus
  tw: Twitter
  tel: Telegram
  ig: Instagram
  msgr: Facebook Messenger
  tumblr: Tumblr
  wp: Wordpress
  wa: WhatsApp
  sc: Soundcloud
